#!/usr/bin/env python3
"""
MCP server wrapping the memos hub API for the Claude Code CEO session.

Exposes three tools:
  memos_search       — FTS + vector search across all hub memories and chunks
  memos_list_skills  — List skills published to the hub
  memos_recent       — Recent memories and tasks on the hub

Credentials are read from environment variables (never passed to the LLM):
  MEMOS_HUB_URL    default: http://localhost:18992
  MEMOS_HUB_TOKEN  required: CEO member token from ~/.claude/memos-hub.env

Start: python3 server.py
Register: claude mcp add memos-hub python3 /path/to/server.py
"""

import json
import os
import sys
import urllib.request
import urllib.error
from typing import Any

from mcp.server.fastmcp import FastMCP

# ─── Credentials from env (never appear in tool args or results) ───
HUB_URL = os.environ.get("MEMOS_HUB_URL", "http://localhost:18992").rstrip("/")
HUB_TOKEN = os.environ.get("MEMOS_HUB_TOKEN", "")

if not HUB_TOKEN:
    print(
        "Error: MEMOS_HUB_TOKEN is not set.\n"
        "Run: source ~/.claude/memos-hub.env before starting the MCP server.\n"
        "Or set MEMOS_HUB_TOKEN in the MCP server's env configuration.",
        file=sys.stderr,
    )
    sys.exit(1)


def _hub_request(method: str, path: str, body: dict | None = None) -> dict:
    url = f"{HUB_URL}{path}"
    data = json.dumps(body).encode() if body is not None else None
    headers = {
        "Authorization": f"Bearer {HUB_TOKEN}",
        "Content-Type": "application/json",
    }
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        body_bytes = e.read()
        raise RuntimeError(f"Hub HTTP {e.code}: {body_bytes.decode()[:200]}") from e
    except urllib.error.URLError as e:
        raise RuntimeError(f"Hub unreachable at {HUB_URL}: {e.reason}") from e


mcp = FastMCP(
    "memos-hub",
    instructions=(
        "Tools for querying the memos hub — a shared memory store for the Hermes "
        "multi-agent system. Use memos_search to find memories from any agent. "
        "Use memos_list_skills to see generated SKILL.md files. "
        "Use memos_recent to browse latest activity."
    ),
)


@mcp.tool()
def memos_search(query: str, max_results: int = 10) -> dict[str, Any]:
    """
    Search the hub for memories and conversation chunks across all agents.

    Returns hits ranked by FTS + vector RRF. Each hit includes:
      - summary: short summary of the memory
      - excerpt: first 240 chars of the content
      - ownerName: hub username of the contributing agent
      - sourceAgent: Hermes profile name (e.g. "research-agent")
      - taskTitle: associated task if available
      - visibility: "public" or group name
      - remoteHitId: opaque ID for fetching full content via memory-detail

    Args:
        query: Full-text / semantic search query.
        max_results: Maximum number of results to return (default 10, max 40).
    """
    max_results = min(max(1, max_results), 40)
    resp = _hub_request("POST", "/api/v1/hub/search", {"query": query, "maxResults": max_results})
    hits = resp.get("hits", [])
    return {
        "query": query,
        "totalHits": len(hits),
        "hits": [
            {
                "rank": h.get("hubRank"),
                "summary": (h.get("summary") or "")[:300],
                "excerpt": (h.get("excerpt") or "")[:240],
                "ownerName": h.get("ownerName", "unknown"),
                "sourceAgent": h.get("sourceAgent", ""),
                "taskTitle": h.get("taskTitle"),
                "visibility": h.get("visibility"),
                "remoteHitId": h.get("remoteHitId"),
            }
            for h in hits
        ],
    }


@mcp.tool()
def memos_list_skills(query: str = "", max_results: int = 20) -> dict[str, Any]:
    """
    List or search skills published to the hub by Hermes agents.

    Skills are SKILL.md files generated by the plugin's skill evolution pipeline.
    Each is a reusable how-to guide distilled from successful agent sessions.

    Args:
        query: Optional search query to filter skills by name/description. Empty = list all.
        max_results: Maximum number of skills to return (default 20).
    """
    max_results = min(max(1, max_results), 40)
    path = f"/api/v1/hub/skills?maxResults={max_results}"
    if query:
        import urllib.parse
        path += f"&query={urllib.parse.quote(query)}"
    resp = _hub_request("GET", path)
    hits = resp.get("hits", [])
    return {
        "query": query or "(all)",
        "totalSkills": len(hits),
        "skills": [
            {
                "skillId": s.get("skillId"),
                "name": s.get("name"),
                "description": (s.get("description") or "")[:200],
                "version": s.get("version"),
                "ownerName": s.get("ownerName", "unknown"),
                "qualityScore": s.get("qualityScore"),
            }
            for s in hits
        ],
    }


@mcp.tool()
def memos_recent(limit: int = 20) -> dict[str, Any]:
    """
    Browse the most recent hub activity: memories and shared tasks.

    Useful for the CEO to get a quick pulse on what agents have been doing.

    Args:
        limit: How many of each type (memories, tasks) to return (default 20, max 40).
    """
    limit = min(max(1, limit), 40)
    memories_resp = _hub_request("GET", f"/api/v1/hub/memories?limit={limit}")
    tasks_resp = _hub_request("GET", f"/api/v1/hub/tasks?limit={limit}")

    memories = memories_resp.get("memories", [])
    tasks = tasks_resp.get("tasks", [])

    return {
        "memories": [
            {
                "id": m.get("id"),
                "summary": (m.get("summary") or "")[:200],
                "sourceAgent": m.get("sourceAgent", ""),
                "role": m.get("role"),
                "visibility": m.get("visibility"),
                "createdAt": m.get("createdAt"),
            }
            for m in memories
        ],
        "tasks": [
            {
                "id": t.get("id"),
                "title": t.get("title"),
                "summary": (t.get("summary") or "")[:200],
                "sourceUserId": t.get("sourceUserId"),
                "visibility": t.get("visibility"),
                "createdAt": t.get("createdAt"),
            }
            for t in tasks
        ],
    }


if __name__ == "__main__":
    mcp.run()
